config/routes.rb
Rails.application.routes.draw do
  resources :speaks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/speak.rb
class Speak < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/speaks_controller.rb
class SpeaksController < ApplicationController
  before_action :set_speak, only: [:show, :edit, :update, :destroy]

  # GET /speaks
  # GET /speaks.json
  def index
    @speaks = Speak.all
  end

  # GET /speaks/1
  # GET /speaks/1.json
  def show
  end

  # GET /speaks/new
  def new
    @speak = Speak.new
  end

  # GET /speaks/1/edit
  def edit
  end

  # POST /speaks
  # POST /speaks.json
  def create
    @speak = Speak.new(speak_params)

    respond_to do |format|
      if @speak.save
        format.html { redirect_to @speak, notice: 'Speak was successfully created.' }
        format.json { render :show, status: :created, location: @speak }
      else
        format.html { render :new }
        format.json { render json: @speak.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speaks/1
  # PATCH/PUT /speaks/1.json
  def update
    respond_to do |format|
      if @speak.update(speak_params)
        format.html { redirect_to @speak, notice: 'Speak was successfully updated.' }
        format.json { render :show, status: :ok, location: @speak }
      else
        format.html { render :edit }
        format.json { render json: @speak.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speaks/1
  # DELETE /speaks/1.json
  def destroy
    @speak.destroy
    respond_to do |format|
      format.html { redirect_to speaks_url, notice: 'Speak was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speak
      @speak = Speak.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speak_params
      params.require(:speak).permit(:speak)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/speaks_helper.rb
module SpeaksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/speaks/_form.html.erb
<%= form_with(model: speak, local: true) do |form| %>
  <% if speak.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(speak.errors.count, "error") %> prohibited this speak from being saved:</h2>

      <ul>
      <% speak.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :speak %>
    <%= form.text_area :speak %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/speaks/edit.html.erb
<h1>Editing Speak</h1>

<%= render 'form', speak: @speak %>

<%= link_to 'Show', @speak %> |
<%= link_to 'Back', speaks_path %>

app/views/speaks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Speaks</h1>

<table>
  <thead>
    <tr>
      <th>Speak</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speaks.each do |speak| %>
      <tr>
        <td><%= speak.speak %></td>
        <td><%= link_to 'Show', speak %></td>
        <td><%= link_to 'Edit', edit_speak_path(speak) %></td>
        <td><%= link_to 'Destroy', speak, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speak', new_speak_path %>

app/views/speaks/new.html.erb
<h1>New Speak</h1>

<%= render 'form', speak: @speak %>

<%= link_to 'Back', speaks_path %>

app/views/speaks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Speak:</strong>
  <%= @speak.speak %>
</p>

<%= link_to 'Edit', edit_speak_path(@speak) %> |
<%= link_to 'Back', speaks_path %>